### PR TITLE
Fix indentation hell

### PR DESCRIPTION
**Pull request by a-catgirl-dev**
and also fixes bugs (1) your code did not account for

### CODE REVIEW

**Comment by a-catgirl-dev** [comment]
@Vaneer420 pwease weview :3 <3 etc
ignore the fact that i called your code bad in discord lmaooo sorry

**Comment by Vaneer420** [comment]
you make me question you a _lot_

**Comment by a-catgirl-dev** [comment]
> you make me question you a _lot_

:-1:

**Comment by a-catgirl-dev** [comment]
POG

**Pull request merged**
