### PR TITLE
Minor loop refactor

### PR DESCRIPTION
**Pull request by a-catgirl-dev**
makes the code not as bad (no offense)

### CODE REVIEW

**Comment by WilliamAnimate** [comment]
wait don't merge yet i just want to see if this code got the green light

**Comment by Vaneer420** [comment]
ig

**Review by Vaneer420 — APPROVED** [review]

**Comment by a-catgirl-dev** [comment]
all done

**Review by Vaneer420 — APPROVED** [review]
ok

**Pull request merged**
